/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthleteError } from "./authleteerror.js";

/**
 * An object containing api_info data
 */
export type ApiInfoErrorData = {
  /**
   * The code which represents the result of the API call.
   */
  resultCode?: string | undefined;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage?: string | undefined;
};

/**
 * An object containing api_info data
 */
export class ApiInfoError extends AuthleteError {
  /**
   * The code which represents the result of the API call.
   */
  resultCode?: string | undefined;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ApiInfoErrorData;

  constructor(
    err: ApiInfoErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.resultCode != null) this.resultCode = err.resultCode;
    if (err.resultMessage != null) this.resultMessage = err.resultMessage;

    this.name = "ApiInfoError";
  }
}

/** @internal */
export const ApiInfoError$inboundSchema: z.ZodType<
  ApiInfoError,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ApiInfoError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ApiInfoError$Outbound = {
  resultCode?: string | undefined;
  resultMessage?: string | undefined;
};

/** @internal */
export const ApiInfoError$outboundSchema: z.ZodType<
  ApiInfoError$Outbound,
  z.ZodTypeDef,
  ApiInfoError
> = z.instanceof(ApiInfoError)
  .transform(v => v.data$)
  .pipe(z.object({
    resultCode: z.string().optional(),
    resultMessage: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiInfoError$ {
  /** @deprecated use `ApiInfoError$inboundSchema` instead. */
  export const inboundSchema = ApiInfoError$inboundSchema;
  /** @deprecated use `ApiInfoError$outboundSchema` instead. */
  export const outboundSchema = ApiInfoError$outboundSchema;
  /** @deprecated use `ApiInfoError$Outbound` instead. */
  export type Outbound = ApiInfoError$Outbound;
}
