/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pushedAuthorizationEndpointPushedAuthReqApi } from "../funcs/pushedAuthorizationEndpointPushedAuthReqApi.js";
import { pushedAuthorizationEndpointPushedAuthReqApiForm } from "../funcs/pushedAuthorizationEndpointPushedAuthReqApiForm.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class PushedAuthorizationEndpoint extends ClientSDK {
  /**
   * Process Pushed Authorization Request
   *
   * @remarks
   * This API creates a pushed request authorization. It authenticates the client and creates a authorization_uri to be returned by the authorization server.
   */
  async pushedAuthReqApi(
    request: operations.PushedAuthReqApiRequest,
    options?: RequestOptions,
  ): Promise<operations.PushedAuthReqApiResponse> {
    return unwrapAsync(pushedAuthorizationEndpointPushedAuthReqApi(
      this,
      request,
      options,
    ));
  }

  /**
   * Process Pushed Authorization Request
   *
   * @remarks
   * This API creates a pushed request authorization. It authenticates the client and creates a authorization_uri to be returned by the authorization server.
   */
  async pushedAuthReqApiForm(
    request: operations.PushedAuthReqApiFormRequest,
    options?: RequestOptions,
  ): Promise<operations.PushedAuthReqApiFormResponse> {
    return unwrapAsync(pushedAuthorizationEndpointPushedAuthReqApiForm(
      this,
      request,
      options,
    ));
  }
}
