/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tokenOperationsAuthTokenCreateApi } from "../funcs/tokenOperationsAuthTokenCreateApi.js";
import { tokenOperationsAuthTokenCreateApiForm } from "../funcs/tokenOperationsAuthTokenCreateApiForm.js";
import { tokenOperationsAuthTokenDeleteApi } from "../funcs/tokenOperationsAuthTokenDeleteApi.js";
import { tokenOperationsAuthTokenGetListApi } from "../funcs/tokenOperationsAuthTokenGetListApi.js";
import { tokenOperationsAuthTokenRevokeApi } from "../funcs/tokenOperationsAuthTokenRevokeApi.js";
import { tokenOperationsAuthTokenRevokeApiForm } from "../funcs/tokenOperationsAuthTokenRevokeApiForm.js";
import { tokenOperationsAuthTokenUpdateApi } from "../funcs/tokenOperationsAuthTokenUpdateApi.js";
import { tokenOperationsAuthTokenUpdateApiForm } from "../funcs/tokenOperationsAuthTokenUpdateApiForm.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class TokenOperations extends ClientSDK {
  /**
   * List Issued Tokens
   *
   * @remarks
   * Get the list of access tokens that are associated with the service.
   */
  async authTokenGetListApi(
    request: operations.AuthTokenGetListApiRequest,
    options?: RequestOptions,
  ): Promise<operations.AuthTokenGetListApiResponse> {
    return unwrapAsync(tokenOperationsAuthTokenGetListApi(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Access Token
   *
   * @remarks
   * Create an access token.
   */
  async authTokenCreateApi(
    request: operations.AuthTokenCreateApiRequest,
    options?: RequestOptions,
  ): Promise<operations.AuthTokenCreateApiResponse> {
    return unwrapAsync(tokenOperationsAuthTokenCreateApi(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Access Token
   *
   * @remarks
   * Create an access token.
   */
  async authTokenCreateApiForm(
    request: operations.AuthTokenCreateApiFormRequest,
    options?: RequestOptions,
  ): Promise<operations.AuthTokenCreateApiFormResponse> {
    return unwrapAsync(tokenOperationsAuthTokenCreateApiForm(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Access Token
   *
   * @remarks
   * Update an access token.
   */
  async authTokenUpdateApi(
    request: operations.AuthTokenUpdateApiRequest,
    options?: RequestOptions,
  ): Promise<operations.AuthTokenUpdateApiResponse> {
    return unwrapAsync(tokenOperationsAuthTokenUpdateApi(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Access Token
   *
   * @remarks
   * Update an access token.
   */
  async authTokenUpdateApiForm(
    request: operations.AuthTokenUpdateApiFormRequest,
    options?: RequestOptions,
  ): Promise<operations.AuthTokenUpdateApiFormResponse> {
    return unwrapAsync(tokenOperationsAuthTokenUpdateApiForm(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Access Token
   *
   * @remarks
   * Delete an access token.
   */
  async authTokenDeleteApi(
    request: operations.AuthTokenDeleteApiRequest,
    options?: RequestOptions,
  ): Promise<operations.AuthTokenDeleteApiResponse> {
    return unwrapAsync(tokenOperationsAuthTokenDeleteApi(
      this,
      request,
      options,
    ));
  }

  /**
   * Revoke Access Token
   *
   * @remarks
   * Revoke an access token.
   */
  async authTokenRevokeApi(
    request: operations.AuthTokenRevokeApiRequest,
    options?: RequestOptions,
  ): Promise<operations.AuthTokenRevokeApiResponse> {
    return unwrapAsync(tokenOperationsAuthTokenRevokeApi(
      this,
      request,
      options,
    ));
  }

  /**
   * Revoke Access Token
   *
   * @remarks
   * Revoke an access token.
   */
  async authTokenRevokeApiForm(
    request: operations.AuthTokenRevokeApiFormRequest,
    options?: RequestOptions,
  ): Promise<operations.AuthTokenRevokeApiFormResponse> {
    return unwrapAsync(tokenOperationsAuthTokenRevokeApiForm(
      this,
      request,
      options,
    ));
  }
}
