workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    authlete-OAS:
        inputs:
            - location: .speakeasy/spec/authlete.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/v0/1/authlete-oas
targets:
    authlete:
        target: typescript
        source: authlete-OAS
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/v0/1/authlete-oas-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
