/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type DeviceVerificationApiFormRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  apilBraceserviceIdRBraceDeviceVerification:
    models.APILBraceserviceIdRBraceDeviceVerification;
};

/**
 * The next action that the authorization server implementation should take.
 */
export const DeviceVerificationApiFormAction = {
  InternalServerError: "INTERNAL_SERVER_ERROR",
  NotExist: "NOT_EXIST",
  Expired: "EXPIRED",
  Valid: "VALID",
} as const;
/**
 * The next action that the authorization server implementation should take.
 */
export type DeviceVerificationApiFormAction = ClosedEnum<
  typeof DeviceVerificationApiFormAction
>;

export type DeviceVerificationApiFormResponse = {
  /**
   * The code which represents the result of the API call.
   */
  resultCode?: string | undefined;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage?: string | undefined;
  /**
   * The next action that the authorization server implementation should take.
   */
  action?: DeviceVerificationApiFormAction | undefined;
  /**
   * The client ID of the client application to which the user code has been issued.
   *
   * @remarks
   */
  clientId?: number | undefined;
  /**
   * The client ID alias of the client application to which the user code has been issued.
   *
   * @remarks
   */
  clientIdAlias?: string | undefined;
  /**
   * `true` if the value of the `client_id` request parameter included in the device authorization
   *
   * @remarks
   * request is the client ID alias. `false` if the value is the original numeric client ID.
   */
  clientIdAliasUsed?: boolean | undefined;
  /**
   * The name of the client application to which the user code has been issued.
   *
   * @remarks
   */
  clientName?: string | undefined;
  /**
   * The scopes requested by the device authorization request.
   *
   * @remarks
   *
   * Note that `description` property and `descriptions` property of each scope object in
   * the array contained in this property is always null even if descriptions of the scopes
   * are registered.
   */
  scopes?: Array<models.Scope> | undefined;
  /**
   * The names of the claims which were requested indirectly via some special scopes.
   *
   * @remarks
   * See [5.4. Requesting Claims using Scope Values](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims)
   * in OpenID Connect Core 1.0 for details.
   *
   * This property is always `null` if the `scope` request parameter of the device authorization
   * request does not include the `openid` scope even if special scopes (such as `profile`)
   * are included in the request (unless the openid scope is included in the default set
   * of scopes which is used when the `scope` request parameter is omitted).
   */
  claimNames?: Array<string> | undefined;
  /**
   * The list of ACR values requested by the device authorization request.
   *
   * @remarks
   */
  acrs?: Array<string> | undefined;
  /**
   * The resources specified by the `resource` request parameters or by the `resource` property
   *
   * @remarks
   * in the request object. If both are given, the values in the request object should be
   * set. See "Resource Indicators for OAuth 2.0" for details.
   */
  resources?: Array<string> | undefined;
  /**
   * The authorization details. This represents the value of the `authorization_details`
   *
   * @remarks
   * request parameter in the preceding device authorization request which is defined in
   * "OAuth 2.0 Rich Authorization Requests".
   */
  authorizationDetails?: models.AuthorizationDetails | undefined;
  /**
   * The attributes of this service that the client application belongs to.
   *
   * @remarks
   */
  serviceAttributes?: Array<models.Pair> | undefined;
  /**
   * The attributes of the client.
   *
   * @remarks
   */
  clientAttributes?: Array<models.Pair> | undefined;
  /**
   * The dynamic scopes which the client application requested by the scope request parameter.
   *
   * @remarks
   */
  dynamicScopes?: Array<models.DynamicScope> | undefined;
  /**
   * Get the date in milliseconds since the Unix epoch (1970-01-01) at which the user code will expire.
   *
   * @remarks
   */
  expiresAt?: number | undefined;
  gmAction?: models.APILBraceserviceIdRBraceGmPropertiesGmAction | undefined;
  /**
   * the value of the `grant_id` request parameter of the device authorization request.
   *
   * @remarks
   *
   * The `grant_id` request parameter is defined in
   * [Grant Management for OAuth 2.0](https://openid.net/specs/fapi-grant-management.html)
   * , which is supported by Authlete 2.3 and newer versions.
   */
  grantId?: string | undefined;
  grant?:
    | models.APILBraceserviceIdRBraceAuthAuthorization200PropertiesGrant
    | undefined;
  /**
   * The subject identifying the user who has given the grant identified
   *
   * @remarks
   * by the `grant_id` request parameter of the device authorization
   * request.
   *
   * Authlete 2.3 and newer versions support <a href=
   * "https://openid.net/specs/fapi-grant-management.html">Grant Management
   * for OAuth 2.0</a>. An authorization request may contain a `grant_id`
   * request parameter which is defined in the specification. If the value of
   * the request parameter is valid, {@link #getGrantSubject()} will return
   * the subject of the user who has given the grant to the client application.
   * Authorization server implementations may use the value returned from
   * {@link #getGrantSubject()} in order to determine the user to authenticate.
   *
   * The user your system will authenticate during the authorization process
   * (or has already authenticated) may be different from the user of the
   * grant. The first implementer's draft of "Grant Management for OAuth 2.0"
   * does not mention anything about the case, so the behavior in the case is
   * left to implementations. Authlete will not perform the grant management
   * action when the `subject` passed to Authlete does not match the
   * user of the grant.
   */
  grantSubject?: string | undefined;
  /**
   * The entity ID of the client.
   *
   * @remarks
   */
  clientEntityId?: string | undefined;
  /**
   * Flag which indicates whether the entity ID of the client was used when the request for the access token was made.
   *
   * @remarks
   */
  clientEntityIdUsed?: boolean | undefined;
};

/** @internal */
export const DeviceVerificationApiFormRequest$inboundSchema: z.ZodType<
  DeviceVerificationApiFormRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  serviceId: z.string(),
  APILBraceserviceIdRBraceDeviceVerification:
    models.APILBraceserviceIdRBraceDeviceVerification$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "APILBraceserviceIdRBraceDeviceVerification":
      "apilBraceserviceIdRBraceDeviceVerification",
  });
});

/** @internal */
export type DeviceVerificationApiFormRequest$Outbound = {
  serviceId: string;
  APILBraceserviceIdRBraceDeviceVerification:
    models.APILBraceserviceIdRBraceDeviceVerification$Outbound;
};

/** @internal */
export const DeviceVerificationApiFormRequest$outboundSchema: z.ZodType<
  DeviceVerificationApiFormRequest$Outbound,
  z.ZodTypeDef,
  DeviceVerificationApiFormRequest
> = z.object({
  serviceId: z.string(),
  apilBraceserviceIdRBraceDeviceVerification:
    models.APILBraceserviceIdRBraceDeviceVerification$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    apilBraceserviceIdRBraceDeviceVerification:
      "APILBraceserviceIdRBraceDeviceVerification",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeviceVerificationApiFormRequest$ {
  /** @deprecated use `DeviceVerificationApiFormRequest$inboundSchema` instead. */
  export const inboundSchema = DeviceVerificationApiFormRequest$inboundSchema;
  /** @deprecated use `DeviceVerificationApiFormRequest$outboundSchema` instead. */
  export const outboundSchema = DeviceVerificationApiFormRequest$outboundSchema;
  /** @deprecated use `DeviceVerificationApiFormRequest$Outbound` instead. */
  export type Outbound = DeviceVerificationApiFormRequest$Outbound;
}

export function deviceVerificationApiFormRequestToJSON(
  deviceVerificationApiFormRequest: DeviceVerificationApiFormRequest,
): string {
  return JSON.stringify(
    DeviceVerificationApiFormRequest$outboundSchema.parse(
      deviceVerificationApiFormRequest,
    ),
  );
}

export function deviceVerificationApiFormRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeviceVerificationApiFormRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeviceVerificationApiFormRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeviceVerificationApiFormRequest' from JSON`,
  );
}

/** @internal */
export const DeviceVerificationApiFormAction$inboundSchema: z.ZodNativeEnum<
  typeof DeviceVerificationApiFormAction
> = z.nativeEnum(DeviceVerificationApiFormAction);

/** @internal */
export const DeviceVerificationApiFormAction$outboundSchema: z.ZodNativeEnum<
  typeof DeviceVerificationApiFormAction
> = DeviceVerificationApiFormAction$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeviceVerificationApiFormAction$ {
  /** @deprecated use `DeviceVerificationApiFormAction$inboundSchema` instead. */
  export const inboundSchema = DeviceVerificationApiFormAction$inboundSchema;
  /** @deprecated use `DeviceVerificationApiFormAction$outboundSchema` instead. */
  export const outboundSchema = DeviceVerificationApiFormAction$outboundSchema;
}

/** @internal */
export const DeviceVerificationApiFormResponse$inboundSchema: z.ZodType<
  DeviceVerificationApiFormResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  action: DeviceVerificationApiFormAction$inboundSchema.optional(),
  clientId: z.number().int().optional(),
  clientIdAlias: z.string().optional(),
  clientIdAliasUsed: z.boolean().optional(),
  clientName: z.string().optional(),
  scopes: z.array(models.Scope$inboundSchema).optional(),
  claimNames: z.array(z.string()).optional(),
  acrs: z.array(z.string()).optional(),
  resources: z.array(z.string()).optional(),
  authorizationDetails: models.AuthorizationDetails$inboundSchema.optional(),
  serviceAttributes: z.array(models.Pair$inboundSchema).optional(),
  clientAttributes: z.array(models.Pair$inboundSchema).optional(),
  dynamicScopes: z.array(models.DynamicScope$inboundSchema).optional(),
  expiresAt: z.number().int().optional(),
  gmAction: models.APILBraceserviceIdRBraceGmPropertiesGmAction$inboundSchema
    .optional(),
  grantId: z.string().optional(),
  grant: models
    .APILBraceserviceIdRBraceAuthAuthorization200PropertiesGrant$inboundSchema
    .optional(),
  grantSubject: z.string().optional(),
  clientEntityId: z.string().optional(),
  clientEntityIdUsed: z.boolean().optional(),
});

/** @internal */
export type DeviceVerificationApiFormResponse$Outbound = {
  resultCode?: string | undefined;
  resultMessage?: string | undefined;
  action?: string | undefined;
  clientId?: number | undefined;
  clientIdAlias?: string | undefined;
  clientIdAliasUsed?: boolean | undefined;
  clientName?: string | undefined;
  scopes?: Array<models.Scope$Outbound> | undefined;
  claimNames?: Array<string> | undefined;
  acrs?: Array<string> | undefined;
  resources?: Array<string> | undefined;
  authorizationDetails?: models.AuthorizationDetails$Outbound | undefined;
  serviceAttributes?: Array<models.Pair$Outbound> | undefined;
  clientAttributes?: Array<models.Pair$Outbound> | undefined;
  dynamicScopes?: Array<models.DynamicScope$Outbound> | undefined;
  expiresAt?: number | undefined;
  gmAction?:
    | models.APILBraceserviceIdRBraceGmPropertiesGmAction$Outbound
    | undefined;
  grantId?: string | undefined;
  grant?:
    | models.APILBraceserviceIdRBraceAuthAuthorization200PropertiesGrant$Outbound
    | undefined;
  grantSubject?: string | undefined;
  clientEntityId?: string | undefined;
  clientEntityIdUsed?: boolean | undefined;
};

/** @internal */
export const DeviceVerificationApiFormResponse$outboundSchema: z.ZodType<
  DeviceVerificationApiFormResponse$Outbound,
  z.ZodTypeDef,
  DeviceVerificationApiFormResponse
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  action: DeviceVerificationApiFormAction$outboundSchema.optional(),
  clientId: z.number().int().optional(),
  clientIdAlias: z.string().optional(),
  clientIdAliasUsed: z.boolean().optional(),
  clientName: z.string().optional(),
  scopes: z.array(models.Scope$outboundSchema).optional(),
  claimNames: z.array(z.string()).optional(),
  acrs: z.array(z.string()).optional(),
  resources: z.array(z.string()).optional(),
  authorizationDetails: models.AuthorizationDetails$outboundSchema.optional(),
  serviceAttributes: z.array(models.Pair$outboundSchema).optional(),
  clientAttributes: z.array(models.Pair$outboundSchema).optional(),
  dynamicScopes: z.array(models.DynamicScope$outboundSchema).optional(),
  expiresAt: z.number().int().optional(),
  gmAction: models.APILBraceserviceIdRBraceGmPropertiesGmAction$outboundSchema
    .optional(),
  grantId: z.string().optional(),
  grant: models
    .APILBraceserviceIdRBraceAuthAuthorization200PropertiesGrant$outboundSchema
    .optional(),
  grantSubject: z.string().optional(),
  clientEntityId: z.string().optional(),
  clientEntityIdUsed: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeviceVerificationApiFormResponse$ {
  /** @deprecated use `DeviceVerificationApiFormResponse$inboundSchema` instead. */
  export const inboundSchema = DeviceVerificationApiFormResponse$inboundSchema;
  /** @deprecated use `DeviceVerificationApiFormResponse$outboundSchema` instead. */
  export const outboundSchema =
    DeviceVerificationApiFormResponse$outboundSchema;
  /** @deprecated use `DeviceVerificationApiFormResponse$Outbound` instead. */
  export type Outbound = DeviceVerificationApiFormResponse$Outbound;
}

export function deviceVerificationApiFormResponseToJSON(
  deviceVerificationApiFormResponse: DeviceVerificationApiFormResponse,
): string {
  return JSON.stringify(
    DeviceVerificationApiFormResponse$outboundSchema.parse(
      deviceVerificationApiFormResponse,
    ),
  );
}

export function deviceVerificationApiFormResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeviceVerificationApiFormResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeviceVerificationApiFormResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeviceVerificationApiFormResponse' from JSON`,
  );
}
