/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type HskGetApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  handle: string;
};

/**
 * Result of the API call
 */
export const HskGetApiAction = {
  Success: "SUCCESS",
  InvalidRequest: "INVALID_REQUEST",
  NotFound: "NOT_FOUND",
  ServerError: "SERVER_ERROR",
} as const;
/**
 * Result of the API call
 */
export type HskGetApiAction = ClosedEnum<typeof HskGetApiAction>;

/**
 * Successful operation
 */
export type HskGetApiResponse = {
  /**
   * The code which represents the result of the API call.
   */
  resultCode?: string | undefined;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage?: string | undefined;
  /**
   * Result of the API call
   */
  action?: HskGetApiAction | undefined;
  /**
   * Holds information about a key managed in an HSM (Hardware Security Module)
   *
   * @remarks
   */
  hsk?: models.Hsk | undefined;
};

/** @internal */
export const HskGetApiRequest$inboundSchema: z.ZodType<
  HskGetApiRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  serviceId: z.string(),
  handle: z.string(),
});

/** @internal */
export type HskGetApiRequest$Outbound = {
  serviceId: string;
  handle: string;
};

/** @internal */
export const HskGetApiRequest$outboundSchema: z.ZodType<
  HskGetApiRequest$Outbound,
  z.ZodTypeDef,
  HskGetApiRequest
> = z.object({
  serviceId: z.string(),
  handle: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace HskGetApiRequest$ {
  /** @deprecated use `HskGetApiRequest$inboundSchema` instead. */
  export const inboundSchema = HskGetApiRequest$inboundSchema;
  /** @deprecated use `HskGetApiRequest$outboundSchema` instead. */
  export const outboundSchema = HskGetApiRequest$outboundSchema;
  /** @deprecated use `HskGetApiRequest$Outbound` instead. */
  export type Outbound = HskGetApiRequest$Outbound;
}

export function hskGetApiRequestToJSON(
  hskGetApiRequest: HskGetApiRequest,
): string {
  return JSON.stringify(
    HskGetApiRequest$outboundSchema.parse(hskGetApiRequest),
  );
}

export function hskGetApiRequestFromJSON(
  jsonString: string,
): SafeParseResult<HskGetApiRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HskGetApiRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HskGetApiRequest' from JSON`,
  );
}

/** @internal */
export const HskGetApiAction$inboundSchema: z.ZodNativeEnum<
  typeof HskGetApiAction
> = z.nativeEnum(HskGetApiAction);

/** @internal */
export const HskGetApiAction$outboundSchema: z.ZodNativeEnum<
  typeof HskGetApiAction
> = HskGetApiAction$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace HskGetApiAction$ {
  /** @deprecated use `HskGetApiAction$inboundSchema` instead. */
  export const inboundSchema = HskGetApiAction$inboundSchema;
  /** @deprecated use `HskGetApiAction$outboundSchema` instead. */
  export const outboundSchema = HskGetApiAction$outboundSchema;
}

/** @internal */
export const HskGetApiResponse$inboundSchema: z.ZodType<
  HskGetApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  action: HskGetApiAction$inboundSchema.optional(),
  hsk: models.Hsk$inboundSchema.optional(),
});

/** @internal */
export type HskGetApiResponse$Outbound = {
  resultCode?: string | undefined;
  resultMessage?: string | undefined;
  action?: string | undefined;
  hsk?: models.Hsk$Outbound | undefined;
};

/** @internal */
export const HskGetApiResponse$outboundSchema: z.ZodType<
  HskGetApiResponse$Outbound,
  z.ZodTypeDef,
  HskGetApiResponse
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  action: HskGetApiAction$outboundSchema.optional(),
  hsk: models.Hsk$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace HskGetApiResponse$ {
  /** @deprecated use `HskGetApiResponse$inboundSchema` instead. */
  export const inboundSchema = HskGetApiResponse$inboundSchema;
  /** @deprecated use `HskGetApiResponse$outboundSchema` instead. */
  export const outboundSchema = HskGetApiResponse$outboundSchema;
  /** @deprecated use `HskGetApiResponse$Outbound` instead. */
  export type Outbound = HskGetApiResponse$Outbound;
}

export function hskGetApiResponseToJSON(
  hskGetApiResponse: HskGetApiResponse,
): string {
  return JSON.stringify(
    HskGetApiResponse$outboundSchema.parse(hskGetApiResponse),
  );
}

export function hskGetApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<HskGetApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HskGetApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HskGetApiResponse' from JSON`,
  );
}
