/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type VciDeferredIssueApiRequestBody = {
  order?: models.CredentialIssuanceOrder | undefined;
};

export type VciDeferredIssueApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  requestBody: VciDeferredIssueApiRequestBody;
};

/**
 * The next action that the implementation of the deferred credential
 *
 * @remarks
 * endpoint should take.
 */
export const VciDeferredIssueApiAction = {
  Ok: "OK",
  Forbidden: "FORBIDDEN",
  InternalServerError: "INTERNAL_SERVER_ERROR",
  CallerError: "CALLER_ERROR",
} as const;
/**
 * The next action that the implementation of the deferred credential
 *
 * @remarks
 * endpoint should take.
 */
export type VciDeferredIssueApiAction = ClosedEnum<
  typeof VciDeferredIssueApiAction
>;

/**
 * Successful operation
 */
export type VciDeferredIssueApiResponse = {
  /**
   * The code which represents the result of the API call.
   */
  resultCode?: string | undefined;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage?: string | undefined;
  /**
   * The next action that the implementation of the deferred credential
   *
   * @remarks
   * endpoint should take.
   */
  action?: VciDeferredIssueApiAction | undefined;
  /**
   * The content of the response that the implementation of the deferred
   *
   * @remarks
   * credential endpoint should return.
   */
  responseContent?: string | undefined;
};

/** @internal */
export const VciDeferredIssueApiRequestBody$inboundSchema: z.ZodType<
  VciDeferredIssueApiRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  order: models.CredentialIssuanceOrder$inboundSchema.optional(),
});

/** @internal */
export type VciDeferredIssueApiRequestBody$Outbound = {
  order?: models.CredentialIssuanceOrder$Outbound | undefined;
};

/** @internal */
export const VciDeferredIssueApiRequestBody$outboundSchema: z.ZodType<
  VciDeferredIssueApiRequestBody$Outbound,
  z.ZodTypeDef,
  VciDeferredIssueApiRequestBody
> = z.object({
  order: models.CredentialIssuanceOrder$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VciDeferredIssueApiRequestBody$ {
  /** @deprecated use `VciDeferredIssueApiRequestBody$inboundSchema` instead. */
  export const inboundSchema = VciDeferredIssueApiRequestBody$inboundSchema;
  /** @deprecated use `VciDeferredIssueApiRequestBody$outboundSchema` instead. */
  export const outboundSchema = VciDeferredIssueApiRequestBody$outboundSchema;
  /** @deprecated use `VciDeferredIssueApiRequestBody$Outbound` instead. */
  export type Outbound = VciDeferredIssueApiRequestBody$Outbound;
}

export function vciDeferredIssueApiRequestBodyToJSON(
  vciDeferredIssueApiRequestBody: VciDeferredIssueApiRequestBody,
): string {
  return JSON.stringify(
    VciDeferredIssueApiRequestBody$outboundSchema.parse(
      vciDeferredIssueApiRequestBody,
    ),
  );
}

export function vciDeferredIssueApiRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<VciDeferredIssueApiRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VciDeferredIssueApiRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VciDeferredIssueApiRequestBody' from JSON`,
  );
}

/** @internal */
export const VciDeferredIssueApiRequest$inboundSchema: z.ZodType<
  VciDeferredIssueApiRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  serviceId: z.string(),
  RequestBody: z.lazy(() => VciDeferredIssueApiRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type VciDeferredIssueApiRequest$Outbound = {
  serviceId: string;
  RequestBody: VciDeferredIssueApiRequestBody$Outbound;
};

/** @internal */
export const VciDeferredIssueApiRequest$outboundSchema: z.ZodType<
  VciDeferredIssueApiRequest$Outbound,
  z.ZodTypeDef,
  VciDeferredIssueApiRequest
> = z.object({
  serviceId: z.string(),
  requestBody: z.lazy(() => VciDeferredIssueApiRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VciDeferredIssueApiRequest$ {
  /** @deprecated use `VciDeferredIssueApiRequest$inboundSchema` instead. */
  export const inboundSchema = VciDeferredIssueApiRequest$inboundSchema;
  /** @deprecated use `VciDeferredIssueApiRequest$outboundSchema` instead. */
  export const outboundSchema = VciDeferredIssueApiRequest$outboundSchema;
  /** @deprecated use `VciDeferredIssueApiRequest$Outbound` instead. */
  export type Outbound = VciDeferredIssueApiRequest$Outbound;
}

export function vciDeferredIssueApiRequestToJSON(
  vciDeferredIssueApiRequest: VciDeferredIssueApiRequest,
): string {
  return JSON.stringify(
    VciDeferredIssueApiRequest$outboundSchema.parse(vciDeferredIssueApiRequest),
  );
}

export function vciDeferredIssueApiRequestFromJSON(
  jsonString: string,
): SafeParseResult<VciDeferredIssueApiRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VciDeferredIssueApiRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VciDeferredIssueApiRequest' from JSON`,
  );
}

/** @internal */
export const VciDeferredIssueApiAction$inboundSchema: z.ZodNativeEnum<
  typeof VciDeferredIssueApiAction
> = z.nativeEnum(VciDeferredIssueApiAction);

/** @internal */
export const VciDeferredIssueApiAction$outboundSchema: z.ZodNativeEnum<
  typeof VciDeferredIssueApiAction
> = VciDeferredIssueApiAction$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VciDeferredIssueApiAction$ {
  /** @deprecated use `VciDeferredIssueApiAction$inboundSchema` instead. */
  export const inboundSchema = VciDeferredIssueApiAction$inboundSchema;
  /** @deprecated use `VciDeferredIssueApiAction$outboundSchema` instead. */
  export const outboundSchema = VciDeferredIssueApiAction$outboundSchema;
}

/** @internal */
export const VciDeferredIssueApiResponse$inboundSchema: z.ZodType<
  VciDeferredIssueApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  action: VciDeferredIssueApiAction$inboundSchema.optional(),
  responseContent: z.string().optional(),
});

/** @internal */
export type VciDeferredIssueApiResponse$Outbound = {
  resultCode?: string | undefined;
  resultMessage?: string | undefined;
  action?: string | undefined;
  responseContent?: string | undefined;
};

/** @internal */
export const VciDeferredIssueApiResponse$outboundSchema: z.ZodType<
  VciDeferredIssueApiResponse$Outbound,
  z.ZodTypeDef,
  VciDeferredIssueApiResponse
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  action: VciDeferredIssueApiAction$outboundSchema.optional(),
  responseContent: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VciDeferredIssueApiResponse$ {
  /** @deprecated use `VciDeferredIssueApiResponse$inboundSchema` instead. */
  export const inboundSchema = VciDeferredIssueApiResponse$inboundSchema;
  /** @deprecated use `VciDeferredIssueApiResponse$outboundSchema` instead. */
  export const outboundSchema = VciDeferredIssueApiResponse$outboundSchema;
  /** @deprecated use `VciDeferredIssueApiResponse$Outbound` instead. */
  export type Outbound = VciDeferredIssueApiResponse$Outbound;
}

export function vciDeferredIssueApiResponseToJSON(
  vciDeferredIssueApiResponse: VciDeferredIssueApiResponse,
): string {
  return JSON.stringify(
    VciDeferredIssueApiResponse$outboundSchema.parse(
      vciDeferredIssueApiResponse,
    ),
  );
}

export function vciDeferredIssueApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<VciDeferredIssueApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VciDeferredIssueApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VciDeferredIssueApiResponse' from JSON`,
  );
}
