/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type APILBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace =
  {};

/** @internal */
export const APILBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace$inboundSchema:
  z.ZodType<
    APILBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace,
    z.ZodTypeDef,
    unknown
  > = z.object({});

/** @internal */
export type APILBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace$Outbound =
  {};

/** @internal */
export const APILBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace$outboundSchema:
  z.ZodType<
    APILBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace$Outbound,
    z.ZodTypeDef,
    APILBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace APILBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace$ {
  /** @deprecated use `APILBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace$inboundSchema` instead. */
  export const inboundSchema =
    APILBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace$inboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace$outboundSchema` instead. */
  export const outboundSchema =
    APILBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace$outboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace$Outbound` instead. */
  export type Outbound =
    APILBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace$Outbound;
}

export function apilBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBraceToJSON(
  apilBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace:
    APILBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace,
): string {
  return JSON.stringify(
    APILBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace$outboundSchema
      .parse(
        apilBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace,
      ),
  );
}

export function apilBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBraceFromJSON(
  jsonString: string,
): SafeParseResult<
  APILBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      APILBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'APILBraceserviceIdRBraceClientAuthorizationUpdateLBraceclientIdRBrace' from JSON`,
  );
}
