/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type APILBraceserviceIdRBraceBackchannelAuthenticationIssue = {};

/** @internal */
export const APILBraceserviceIdRBraceBackchannelAuthenticationIssue$inboundSchema:
  z.ZodType<
    APILBraceserviceIdRBraceBackchannelAuthenticationIssue,
    z.ZodTypeDef,
    unknown
  > = z.object({});

/** @internal */
export type APILBraceserviceIdRBraceBackchannelAuthenticationIssue$Outbound =
  {};

/** @internal */
export const APILBraceserviceIdRBraceBackchannelAuthenticationIssue$outboundSchema:
  z.ZodType<
    APILBraceserviceIdRBraceBackchannelAuthenticationIssue$Outbound,
    z.ZodTypeDef,
    APILBraceserviceIdRBraceBackchannelAuthenticationIssue
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace APILBraceserviceIdRBraceBackchannelAuthenticationIssue$ {
  /** @deprecated use `APILBraceserviceIdRBraceBackchannelAuthenticationIssue$inboundSchema` instead. */
  export const inboundSchema =
    APILBraceserviceIdRBraceBackchannelAuthenticationIssue$inboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceBackchannelAuthenticationIssue$outboundSchema` instead. */
  export const outboundSchema =
    APILBraceserviceIdRBraceBackchannelAuthenticationIssue$outboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceBackchannelAuthenticationIssue$Outbound` instead. */
  export type Outbound =
    APILBraceserviceIdRBraceBackchannelAuthenticationIssue$Outbound;
}

export function apilBraceserviceIdRBraceBackchannelAuthenticationIssueToJSON(
  apilBraceserviceIdRBraceBackchannelAuthenticationIssue:
    APILBraceserviceIdRBraceBackchannelAuthenticationIssue,
): string {
  return JSON.stringify(
    APILBraceserviceIdRBraceBackchannelAuthenticationIssue$outboundSchema.parse(
      apilBraceserviceIdRBraceBackchannelAuthenticationIssue,
    ),
  );
}

export function apilBraceserviceIdRBraceBackchannelAuthenticationIssueFromJSON(
  jsonString: string,
): SafeParseResult<
  APILBraceserviceIdRBraceBackchannelAuthenticationIssue,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      APILBraceserviceIdRBraceBackchannelAuthenticationIssue$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'APILBraceserviceIdRBraceBackchannelAuthenticationIssue' from JSON`,
  );
}
