/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type APILBraceserviceIdRBraceAuthAuthorizationFail = {};

/** @internal */
export const APILBraceserviceIdRBraceAuthAuthorizationFail$inboundSchema:
  z.ZodType<
    APILBraceserviceIdRBraceAuthAuthorizationFail,
    z.ZodTypeDef,
    unknown
  > = z.object({});

/** @internal */
export type APILBraceserviceIdRBraceAuthAuthorizationFail$Outbound = {};

/** @internal */
export const APILBraceserviceIdRBraceAuthAuthorizationFail$outboundSchema:
  z.ZodType<
    APILBraceserviceIdRBraceAuthAuthorizationFail$Outbound,
    z.ZodTypeDef,
    APILBraceserviceIdRBraceAuthAuthorizationFail
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace APILBraceserviceIdRBraceAuthAuthorizationFail$ {
  /** @deprecated use `APILBraceserviceIdRBraceAuthAuthorizationFail$inboundSchema` instead. */
  export const inboundSchema =
    APILBraceserviceIdRBraceAuthAuthorizationFail$inboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceAuthAuthorizationFail$outboundSchema` instead. */
  export const outboundSchema =
    APILBraceserviceIdRBraceAuthAuthorizationFail$outboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceAuthAuthorizationFail$Outbound` instead. */
  export type Outbound = APILBraceserviceIdRBraceAuthAuthorizationFail$Outbound;
}

export function apilBraceserviceIdRBraceAuthAuthorizationFailToJSON(
  apilBraceserviceIdRBraceAuthAuthorizationFail:
    APILBraceserviceIdRBraceAuthAuthorizationFail,
): string {
  return JSON.stringify(
    APILBraceserviceIdRBraceAuthAuthorizationFail$outboundSchema.parse(
      apilBraceserviceIdRBraceAuthAuthorizationFail,
    ),
  );
}

export function apilBraceserviceIdRBraceAuthAuthorizationFailFromJSON(
  jsonString: string,
): SafeParseResult<
  APILBraceserviceIdRBraceAuthAuthorizationFail,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      APILBraceserviceIdRBraceAuthAuthorizationFail$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'APILBraceserviceIdRBraceAuthAuthorizationFail' from JSON`,
  );
}
