/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type APILBraceserviceIdRBraceVciOfferInfo = {};

/** @internal */
export const APILBraceserviceIdRBraceVciOfferInfo$inboundSchema: z.ZodType<
  APILBraceserviceIdRBraceVciOfferInfo,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type APILBraceserviceIdRBraceVciOfferInfo$Outbound = {};

/** @internal */
export const APILBraceserviceIdRBraceVciOfferInfo$outboundSchema: z.ZodType<
  APILBraceserviceIdRBraceVciOfferInfo$Outbound,
  z.ZodTypeDef,
  APILBraceserviceIdRBraceVciOfferInfo
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace APILBraceserviceIdRBraceVciOfferInfo$ {
  /** @deprecated use `APILBraceserviceIdRBraceVciOfferInfo$inboundSchema` instead. */
  export const inboundSchema =
    APILBraceserviceIdRBraceVciOfferInfo$inboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceVciOfferInfo$outboundSchema` instead. */
  export const outboundSchema =
    APILBraceserviceIdRBraceVciOfferInfo$outboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceVciOfferInfo$Outbound` instead. */
  export type Outbound = APILBraceserviceIdRBraceVciOfferInfo$Outbound;
}

export function apilBraceserviceIdRBraceVciOfferInfoToJSON(
  apilBraceserviceIdRBraceVciOfferInfo: APILBraceserviceIdRBraceVciOfferInfo,
): string {
  return JSON.stringify(
    APILBraceserviceIdRBraceVciOfferInfo$outboundSchema.parse(
      apilBraceserviceIdRBraceVciOfferInfo,
    ),
  );
}

export function apilBraceserviceIdRBraceVciOfferInfoFromJSON(
  jsonString: string,
): SafeParseResult<APILBraceserviceIdRBraceVciOfferInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      APILBraceserviceIdRBraceVciOfferInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'APILBraceserviceIdRBraceVciOfferInfo' from JSON`,
  );
}
