/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type APILBraceserviceIdRBraceAuthAuthorization = {};

/** @internal */
export const APILBraceserviceIdRBraceAuthAuthorization$inboundSchema: z.ZodType<
  APILBraceserviceIdRBraceAuthAuthorization,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type APILBraceserviceIdRBraceAuthAuthorization$Outbound = {};

/** @internal */
export const APILBraceserviceIdRBraceAuthAuthorization$outboundSchema:
  z.ZodType<
    APILBraceserviceIdRBraceAuthAuthorization$Outbound,
    z.ZodTypeDef,
    APILBraceserviceIdRBraceAuthAuthorization
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace APILBraceserviceIdRBraceAuthAuthorization$ {
  /** @deprecated use `APILBraceserviceIdRBraceAuthAuthorization$inboundSchema` instead. */
  export const inboundSchema =
    APILBraceserviceIdRBraceAuthAuthorization$inboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceAuthAuthorization$outboundSchema` instead. */
  export const outboundSchema =
    APILBraceserviceIdRBraceAuthAuthorization$outboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceAuthAuthorization$Outbound` instead. */
  export type Outbound = APILBraceserviceIdRBraceAuthAuthorization$Outbound;
}

export function apilBraceserviceIdRBraceAuthAuthorizationToJSON(
  apilBraceserviceIdRBraceAuthAuthorization:
    APILBraceserviceIdRBraceAuthAuthorization,
): string {
  return JSON.stringify(
    APILBraceserviceIdRBraceAuthAuthorization$outboundSchema.parse(
      apilBraceserviceIdRBraceAuthAuthorization,
    ),
  );
}

export function apilBraceserviceIdRBraceAuthAuthorizationFromJSON(
  jsonString: string,
): SafeParseResult<
  APILBraceserviceIdRBraceAuthAuthorization,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      APILBraceserviceIdRBraceAuthAuthorization$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'APILBraceserviceIdRBraceAuthAuthorization' from JSON`,
  );
}
