/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type APILBraceserviceIdRBraceAuthAuthorizationIssue = {};

/** @internal */
export const APILBraceserviceIdRBraceAuthAuthorizationIssue$inboundSchema:
  z.ZodType<
    APILBraceserviceIdRBraceAuthAuthorizationIssue,
    z.ZodTypeDef,
    unknown
  > = z.object({});

/** @internal */
export type APILBraceserviceIdRBraceAuthAuthorizationIssue$Outbound = {};

/** @internal */
export const APILBraceserviceIdRBraceAuthAuthorizationIssue$outboundSchema:
  z.ZodType<
    APILBraceserviceIdRBraceAuthAuthorizationIssue$Outbound,
    z.ZodTypeDef,
    APILBraceserviceIdRBraceAuthAuthorizationIssue
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace APILBraceserviceIdRBraceAuthAuthorizationIssue$ {
  /** @deprecated use `APILBraceserviceIdRBraceAuthAuthorizationIssue$inboundSchema` instead. */
  export const inboundSchema =
    APILBraceserviceIdRBraceAuthAuthorizationIssue$inboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceAuthAuthorizationIssue$outboundSchema` instead. */
  export const outboundSchema =
    APILBraceserviceIdRBraceAuthAuthorizationIssue$outboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceAuthAuthorizationIssue$Outbound` instead. */
  export type Outbound =
    APILBraceserviceIdRBraceAuthAuthorizationIssue$Outbound;
}

export function apilBraceserviceIdRBraceAuthAuthorizationIssueToJSON(
  apilBraceserviceIdRBraceAuthAuthorizationIssue:
    APILBraceserviceIdRBraceAuthAuthorizationIssue,
): string {
  return JSON.stringify(
    APILBraceserviceIdRBraceAuthAuthorizationIssue$outboundSchema.parse(
      apilBraceserviceIdRBraceAuthAuthorizationIssue,
    ),
  );
}

export function apilBraceserviceIdRBraceAuthAuthorizationIssueFromJSON(
  jsonString: string,
): SafeParseResult<
  APILBraceserviceIdRBraceAuthAuthorizationIssue,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      APILBraceserviceIdRBraceAuthAuthorizationIssue$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'APILBraceserviceIdRBraceAuthAuthorizationIssue' from JSON`,
  );
}
