/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type APILBraceserviceIdRBraceBackchannelAuthenticationFail = {};

/** @internal */
export const APILBraceserviceIdRBraceBackchannelAuthenticationFail$inboundSchema:
  z.ZodType<
    APILBraceserviceIdRBraceBackchannelAuthenticationFail,
    z.ZodTypeDef,
    unknown
  > = z.object({});

/** @internal */
export type APILBraceserviceIdRBraceBackchannelAuthenticationFail$Outbound = {};

/** @internal */
export const APILBraceserviceIdRBraceBackchannelAuthenticationFail$outboundSchema:
  z.ZodType<
    APILBraceserviceIdRBraceBackchannelAuthenticationFail$Outbound,
    z.ZodTypeDef,
    APILBraceserviceIdRBraceBackchannelAuthenticationFail
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace APILBraceserviceIdRBraceBackchannelAuthenticationFail$ {
  /** @deprecated use `APILBraceserviceIdRBraceBackchannelAuthenticationFail$inboundSchema` instead. */
  export const inboundSchema =
    APILBraceserviceIdRBraceBackchannelAuthenticationFail$inboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceBackchannelAuthenticationFail$outboundSchema` instead. */
  export const outboundSchema =
    APILBraceserviceIdRBraceBackchannelAuthenticationFail$outboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceBackchannelAuthenticationFail$Outbound` instead. */
  export type Outbound =
    APILBraceserviceIdRBraceBackchannelAuthenticationFail$Outbound;
}

export function apilBraceserviceIdRBraceBackchannelAuthenticationFailToJSON(
  apilBraceserviceIdRBraceBackchannelAuthenticationFail:
    APILBraceserviceIdRBraceBackchannelAuthenticationFail,
): string {
  return JSON.stringify(
    APILBraceserviceIdRBraceBackchannelAuthenticationFail$outboundSchema.parse(
      apilBraceserviceIdRBraceBackchannelAuthenticationFail,
    ),
  );
}

export function apilBraceserviceIdRBraceBackchannelAuthenticationFailFromJSON(
  jsonString: string,
): SafeParseResult<
  APILBraceserviceIdRBraceBackchannelAuthenticationFail,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      APILBraceserviceIdRBraceBackchannelAuthenticationFail$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'APILBraceserviceIdRBraceBackchannelAuthenticationFail' from JSON`,
  );
}
