/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type APILBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200 =
  {};

/** @internal */
export const APILBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200$inboundSchema:
  z.ZodType<
    APILBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200,
    z.ZodTypeDef,
    unknown
  > = z.object({});

/** @internal */
export type APILBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200$Outbound =
  {};

/** @internal */
export const APILBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200$outboundSchema:
  z.ZodType<
    APILBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200$Outbound,
    z.ZodTypeDef,
    APILBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace APILBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200$ {
  /** @deprecated use `APILBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200$inboundSchema` instead. */
  export const inboundSchema =
    APILBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200$inboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200$outboundSchema` instead. */
  export const outboundSchema =
    APILBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200$outboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200$Outbound` instead. */
  export type Outbound =
    APILBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200$Outbound;
}

export function apilBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200ToJSON(
  apilBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200:
    APILBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200,
): string {
  return JSON.stringify(
    APILBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200$outboundSchema
      .parse(
        apilBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200,
      ),
  );
}

export function apilBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200FromJSON(
  jsonString: string,
): SafeParseResult<
  APILBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      APILBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'APILBraceserviceIdRBraceClientGrantedScopesLBraceclientIdRBrace200' from JSON`,
  );
}
