/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type APILBraceserviceIdRBraceVciJwks = {};

/** @internal */
export const APILBraceserviceIdRBraceVciJwks$inboundSchema: z.ZodType<
  APILBraceserviceIdRBraceVciJwks,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type APILBraceserviceIdRBraceVciJwks$Outbound = {};

/** @internal */
export const APILBraceserviceIdRBraceVciJwks$outboundSchema: z.ZodType<
  APILBraceserviceIdRBraceVciJwks$Outbound,
  z.ZodTypeDef,
  APILBraceserviceIdRBraceVciJwks
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace APILBraceserviceIdRBraceVciJwks$ {
  /** @deprecated use `APILBraceserviceIdRBraceVciJwks$inboundSchema` instead. */
  export const inboundSchema = APILBraceserviceIdRBraceVciJwks$inboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceVciJwks$outboundSchema` instead. */
  export const outboundSchema = APILBraceserviceIdRBraceVciJwks$outboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceVciJwks$Outbound` instead. */
  export type Outbound = APILBraceserviceIdRBraceVciJwks$Outbound;
}

export function apilBraceserviceIdRBraceVciJwksToJSON(
  apilBraceserviceIdRBraceVciJwks: APILBraceserviceIdRBraceVciJwks,
): string {
  return JSON.stringify(
    APILBraceserviceIdRBraceVciJwks$outboundSchema.parse(
      apilBraceserviceIdRBraceVciJwks,
    ),
  );
}

export function apilBraceserviceIdRBraceVciJwksFromJSON(
  jsonString: string,
): SafeParseResult<APILBraceserviceIdRBraceVciJwks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => APILBraceserviceIdRBraceVciJwks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'APILBraceserviceIdRBraceVciJwks' from JSON`,
  );
}
