/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type APILBraceserviceIdRBraceVciOfferCreate = {};

/** @internal */
export const APILBraceserviceIdRBraceVciOfferCreate$inboundSchema: z.ZodType<
  APILBraceserviceIdRBraceVciOfferCreate,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type APILBraceserviceIdRBraceVciOfferCreate$Outbound = {};

/** @internal */
export const APILBraceserviceIdRBraceVciOfferCreate$outboundSchema: z.ZodType<
  APILBraceserviceIdRBraceVciOfferCreate$Outbound,
  z.ZodTypeDef,
  APILBraceserviceIdRBraceVciOfferCreate
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace APILBraceserviceIdRBraceVciOfferCreate$ {
  /** @deprecated use `APILBraceserviceIdRBraceVciOfferCreate$inboundSchema` instead. */
  export const inboundSchema =
    APILBraceserviceIdRBraceVciOfferCreate$inboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceVciOfferCreate$outboundSchema` instead. */
  export const outboundSchema =
    APILBraceserviceIdRBraceVciOfferCreate$outboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceVciOfferCreate$Outbound` instead. */
  export type Outbound = APILBraceserviceIdRBraceVciOfferCreate$Outbound;
}

export function apilBraceserviceIdRBraceVciOfferCreateToJSON(
  apilBraceserviceIdRBraceVciOfferCreate:
    APILBraceserviceIdRBraceVciOfferCreate,
): string {
  return JSON.stringify(
    APILBraceserviceIdRBraceVciOfferCreate$outboundSchema.parse(
      apilBraceserviceIdRBraceVciOfferCreate,
    ),
  );
}

export function apilBraceserviceIdRBraceVciOfferCreateFromJSON(
  jsonString: string,
): SafeParseResult<APILBraceserviceIdRBraceVciOfferCreate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      APILBraceserviceIdRBraceVciOfferCreate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'APILBraceserviceIdRBraceVciOfferCreate' from JSON`,
  );
}
