/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type APILBraceserviceIdRBraceAuthIntrospection = {};

/** @internal */
export const APILBraceserviceIdRBraceAuthIntrospection$inboundSchema: z.ZodType<
  APILBraceserviceIdRBraceAuthIntrospection,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type APILBraceserviceIdRBraceAuthIntrospection$Outbound = {};

/** @internal */
export const APILBraceserviceIdRBraceAuthIntrospection$outboundSchema:
  z.ZodType<
    APILBraceserviceIdRBraceAuthIntrospection$Outbound,
    z.ZodTypeDef,
    APILBraceserviceIdRBraceAuthIntrospection
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace APILBraceserviceIdRBraceAuthIntrospection$ {
  /** @deprecated use `APILBraceserviceIdRBraceAuthIntrospection$inboundSchema` instead. */
  export const inboundSchema =
    APILBraceserviceIdRBraceAuthIntrospection$inboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceAuthIntrospection$outboundSchema` instead. */
  export const outboundSchema =
    APILBraceserviceIdRBraceAuthIntrospection$outboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceAuthIntrospection$Outbound` instead. */
  export type Outbound = APILBraceserviceIdRBraceAuthIntrospection$Outbound;
}

export function apilBraceserviceIdRBraceAuthIntrospectionToJSON(
  apilBraceserviceIdRBraceAuthIntrospection:
    APILBraceserviceIdRBraceAuthIntrospection,
): string {
  return JSON.stringify(
    APILBraceserviceIdRBraceAuthIntrospection$outboundSchema.parse(
      apilBraceserviceIdRBraceAuthIntrospection,
    ),
  );
}

export function apilBraceserviceIdRBraceAuthIntrospectionFromJSON(
  jsonString: string,
): SafeParseResult<
  APILBraceserviceIdRBraceAuthIntrospection,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      APILBraceserviceIdRBraceAuthIntrospection$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'APILBraceserviceIdRBraceAuthIntrospection' from JSON`,
  );
}
