/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type APILBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace =
  {};

/** @internal */
export const APILBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace$inboundSchema:
  z.ZodType<
    APILBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace,
    z.ZodTypeDef,
    unknown
  > = z.object({});

/** @internal */
export type APILBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace$Outbound =
  {};

/** @internal */
export const APILBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace$outboundSchema:
  z.ZodType<
    APILBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace$Outbound,
    z.ZodTypeDef,
    APILBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace APILBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace$ {
  /** @deprecated use `APILBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace$inboundSchema` instead. */
  export const inboundSchema =
    APILBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace$inboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace$outboundSchema` instead. */
  export const outboundSchema =
    APILBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace$outboundSchema;
  /** @deprecated use `APILBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace$Outbound` instead. */
  export type Outbound =
    APILBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace$Outbound;
}

export function apilBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBraceToJSON(
  apilBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace:
    APILBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace,
): string {
  return JSON.stringify(
    APILBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace$outboundSchema
      .parse(
        apilBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace,
      ),
  );
}

export function apilBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBraceFromJSON(
  jsonString: string,
): SafeParseResult<
  APILBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      APILBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'APILBraceserviceIdRBraceClientSecretUpdateLBraceclientIdentifierRBrace' from JSON`,
  );
}
