/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AuthorizationDetails,
  AuthorizationDetails$inboundSchema,
  AuthorizationDetails$Outbound,
  AuthorizationDetails$outboundSchema,
} from "./authorizationdetails.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * An object containing items data
 */
export type ApiServiceIdAuthAuthorizationpropertiesgrantScope = {
  /**
   * Space-delimited scopes.
   *
   * @remarks
   */
  scope?: string | undefined;
  /**
   * List of resource indicators.
   *
   * @remarks
   */
  resource?: Array<string> | undefined;
};

/**
 * An object containing api_serviceid_auth_authorizationpropertiesgrant data
 */
export type ApiServiceIdAuthAuthorizationpropertiesgrant = {
  /**
   * An array of scopes items
   */
  scopes?: Array<ApiServiceIdAuthAuthorizationpropertiesgrantScope> | undefined;
  /**
   * The claims associated with the Grant.
   *
   * @remarks
   */
  claims?: Array<string> | undefined;
  /**
   * The authorization details. This represents the value of the `authorization_details`
   *
   * @remarks
   * request parameter in the preceding device authorization request which is defined in
   * "OAuth 2.0 Rich Authorization Requests".
   */
  authorizationDetails?: AuthorizationDetails | undefined;
};

/** @internal */
export const ApiServiceIdAuthAuthorizationpropertiesgrantScope$inboundSchema:
  z.ZodType<
    ApiServiceIdAuthAuthorizationpropertiesgrantScope,
    z.ZodTypeDef,
    unknown
  > = z.object({
    scope: z.string().optional(),
    resource: z.array(z.string()).optional(),
  });

/** @internal */
export type ApiServiceIdAuthAuthorizationpropertiesgrantScope$Outbound = {
  scope?: string | undefined;
  resource?: Array<string> | undefined;
};

/** @internal */
export const ApiServiceIdAuthAuthorizationpropertiesgrantScope$outboundSchema:
  z.ZodType<
    ApiServiceIdAuthAuthorizationpropertiesgrantScope$Outbound,
    z.ZodTypeDef,
    ApiServiceIdAuthAuthorizationpropertiesgrantScope
  > = z.object({
    scope: z.string().optional(),
    resource: z.array(z.string()).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiServiceIdAuthAuthorizationpropertiesgrantScope$ {
  /** @deprecated use `ApiServiceIdAuthAuthorizationpropertiesgrantScope$inboundSchema` instead. */
  export const inboundSchema =
    ApiServiceIdAuthAuthorizationpropertiesgrantScope$inboundSchema;
  /** @deprecated use `ApiServiceIdAuthAuthorizationpropertiesgrantScope$outboundSchema` instead. */
  export const outboundSchema =
    ApiServiceIdAuthAuthorizationpropertiesgrantScope$outboundSchema;
  /** @deprecated use `ApiServiceIdAuthAuthorizationpropertiesgrantScope$Outbound` instead. */
  export type Outbound =
    ApiServiceIdAuthAuthorizationpropertiesgrantScope$Outbound;
}

export function apiServiceIdAuthAuthorizationpropertiesgrantScopeToJSON(
  apiServiceIdAuthAuthorizationpropertiesgrantScope:
    ApiServiceIdAuthAuthorizationpropertiesgrantScope,
): string {
  return JSON.stringify(
    ApiServiceIdAuthAuthorizationpropertiesgrantScope$outboundSchema.parse(
      apiServiceIdAuthAuthorizationpropertiesgrantScope,
    ),
  );
}

export function apiServiceIdAuthAuthorizationpropertiesgrantScopeFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiServiceIdAuthAuthorizationpropertiesgrantScope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiServiceIdAuthAuthorizationpropertiesgrantScope$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiServiceIdAuthAuthorizationpropertiesgrantScope' from JSON`,
  );
}

/** @internal */
export const ApiServiceIdAuthAuthorizationpropertiesgrant$inboundSchema:
  z.ZodType<
    ApiServiceIdAuthAuthorizationpropertiesgrant,
    z.ZodTypeDef,
    unknown
  > = z.object({
    scopes: z.array(
      z.lazy(() =>
        ApiServiceIdAuthAuthorizationpropertiesgrantScope$inboundSchema
      ),
    ).optional(),
    claims: z.array(z.string()).optional(),
    authorizationDetails: AuthorizationDetails$inboundSchema.optional(),
  });

/** @internal */
export type ApiServiceIdAuthAuthorizationpropertiesgrant$Outbound = {
  scopes?:
    | Array<ApiServiceIdAuthAuthorizationpropertiesgrantScope$Outbound>
    | undefined;
  claims?: Array<string> | undefined;
  authorizationDetails?: AuthorizationDetails$Outbound | undefined;
};

/** @internal */
export const ApiServiceIdAuthAuthorizationpropertiesgrant$outboundSchema:
  z.ZodType<
    ApiServiceIdAuthAuthorizationpropertiesgrant$Outbound,
    z.ZodTypeDef,
    ApiServiceIdAuthAuthorizationpropertiesgrant
  > = z.object({
    scopes: z.array(
      z.lazy(() =>
        ApiServiceIdAuthAuthorizationpropertiesgrantScope$outboundSchema
      ),
    ).optional(),
    claims: z.array(z.string()).optional(),
    authorizationDetails: AuthorizationDetails$outboundSchema.optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiServiceIdAuthAuthorizationpropertiesgrant$ {
  /** @deprecated use `ApiServiceIdAuthAuthorizationpropertiesgrant$inboundSchema` instead. */
  export const inboundSchema =
    ApiServiceIdAuthAuthorizationpropertiesgrant$inboundSchema;
  /** @deprecated use `ApiServiceIdAuthAuthorizationpropertiesgrant$outboundSchema` instead. */
  export const outboundSchema =
    ApiServiceIdAuthAuthorizationpropertiesgrant$outboundSchema;
  /** @deprecated use `ApiServiceIdAuthAuthorizationpropertiesgrant$Outbound` instead. */
  export type Outbound = ApiServiceIdAuthAuthorizationpropertiesgrant$Outbound;
}

export function apiServiceIdAuthAuthorizationpropertiesgrantToJSON(
  apiServiceIdAuthAuthorizationpropertiesgrant:
    ApiServiceIdAuthAuthorizationpropertiesgrant,
): string {
  return JSON.stringify(
    ApiServiceIdAuthAuthorizationpropertiesgrant$outboundSchema.parse(
      apiServiceIdAuthAuthorizationpropertiesgrant,
    ),
  );
}

export function apiServiceIdAuthAuthorizationpropertiesgrantFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiServiceIdAuthAuthorizationpropertiesgrant,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiServiceIdAuthAuthorizationpropertiesgrant$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiServiceIdAuthAuthorizationpropertiesgrant' from JSON`,
  );
}
