/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * An object containing api_serviceid_client_registration data
 */
export type ApiServiceIdClientRegistration = {
  /**
   * Client metadata in JSON format that complies with [RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591)
   *
   * @remarks
   * (OAuth 2.0 Dynamic Client Registration Protocol).
   */
  json: string;
  /**
   * The client registration access token. Used only for GET, UPDATE, and DELETE requests.
   *
   * @remarks
   */
  token?: string | undefined;
  /**
   * The client's identifier. Used for GET, UPDATE, and DELETE requests
   *
   * @remarks
   */
  clientId?: number | undefined;
};

/** @internal */
export const ApiServiceIdClientRegistration$inboundSchema: z.ZodType<
  ApiServiceIdClientRegistration,
  z.ZodTypeDef,
  unknown
> = z.object({
  json: z.string(),
  token: z.string().optional(),
  clientId: z.number().int().optional(),
});

/** @internal */
export type ApiServiceIdClientRegistration$Outbound = {
  json: string;
  token?: string | undefined;
  clientId?: number | undefined;
};

/** @internal */
export const ApiServiceIdClientRegistration$outboundSchema: z.ZodType<
  ApiServiceIdClientRegistration$Outbound,
  z.ZodTypeDef,
  ApiServiceIdClientRegistration
> = z.object({
  json: z.string(),
  token: z.string().optional(),
  clientId: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiServiceIdClientRegistration$ {
  /** @deprecated use `ApiServiceIdClientRegistration$inboundSchema` instead. */
  export const inboundSchema = ApiServiceIdClientRegistration$inboundSchema;
  /** @deprecated use `ApiServiceIdClientRegistration$outboundSchema` instead. */
  export const outboundSchema = ApiServiceIdClientRegistration$outboundSchema;
  /** @deprecated use `ApiServiceIdClientRegistration$Outbound` instead. */
  export type Outbound = ApiServiceIdClientRegistration$Outbound;
}

export function apiServiceIdClientRegistrationToJSON(
  apiServiceIdClientRegistration: ApiServiceIdClientRegistration,
): string {
  return JSON.stringify(
    ApiServiceIdClientRegistration$outboundSchema.parse(
      apiServiceIdClientRegistration,
    ),
  );
}

export function apiServiceIdClientRegistrationFromJSON(
  jsonString: string,
): SafeParseResult<ApiServiceIdClientRegistration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiServiceIdClientRegistration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiServiceIdClientRegistration' from JSON`,
  );
}
