/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The grant management action of the device authorization request.
 *
 * @remarks
 *
 * The `grant_management_action` request parameter is defined in
 * [Grant Management for OAuth 2.0](https://openid.net/specs/fapi-grant-management.html).
 */
export const ApiServiceIdGmpropertiesgmAction = {
  Create: "CREATE",
  Query: "QUERY",
  Replace: "REPLACE",
  Revoke: "REVOKE",
  Merge: "MERGE",
} as const;
/**
 * The grant management action of the device authorization request.
 *
 * @remarks
 *
 * The `grant_management_action` request parameter is defined in
 * [Grant Management for OAuth 2.0](https://openid.net/specs/fapi-grant-management.html).
 */
export type ApiServiceIdGmpropertiesgmAction = ClosedEnum<
  typeof ApiServiceIdGmpropertiesgmAction
>;

/** @internal */
export const ApiServiceIdGmpropertiesgmAction$inboundSchema: z.ZodNativeEnum<
  typeof ApiServiceIdGmpropertiesgmAction
> = z.nativeEnum(ApiServiceIdGmpropertiesgmAction);

/** @internal */
export const ApiServiceIdGmpropertiesgmAction$outboundSchema: z.ZodNativeEnum<
  typeof ApiServiceIdGmpropertiesgmAction
> = ApiServiceIdGmpropertiesgmAction$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiServiceIdGmpropertiesgmAction$ {
  /** @deprecated use `ApiServiceIdGmpropertiesgmAction$inboundSchema` instead. */
  export const inboundSchema = ApiServiceIdGmpropertiesgmAction$inboundSchema;
  /** @deprecated use `ApiServiceIdGmpropertiesgmAction$outboundSchema` instead. */
  export const outboundSchema = ApiServiceIdGmpropertiesgmAction$outboundSchema;
}
