/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The grant management action of the device authorization request.
 *
 * @remarks
 *
 * The `grant_management_action` request parameter is defined in
 * [Grant Management for OAuth 2.0](https://openid.net/specs/fapi-grant-management.html).
 */
export const ApiServiceIdGmpropertiesgmAction2 = {
  Create: "CREATE",
  Query: "QUERY",
  Replace: "REPLACE",
  Revoke: "REVOKE",
  Merge: "MERGE",
} as const;
/**
 * The grant management action of the device authorization request.
 *
 * @remarks
 *
 * The `grant_management_action` request parameter is defined in
 * [Grant Management for OAuth 2.0](https://openid.net/specs/fapi-grant-management.html).
 */
export type ApiServiceIdGmpropertiesgmAction2 = ClosedEnum<
  typeof ApiServiceIdGmpropertiesgmAction2
>;

/** @internal */
export const ApiServiceIdGmpropertiesgmAction2$inboundSchema: z.ZodNativeEnum<
  typeof ApiServiceIdGmpropertiesgmAction2
> = z.nativeEnum(ApiServiceIdGmpropertiesgmAction2);

/** @internal */
export const ApiServiceIdGmpropertiesgmAction2$outboundSchema: z.ZodNativeEnum<
  typeof ApiServiceIdGmpropertiesgmAction2
> = ApiServiceIdGmpropertiesgmAction2$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiServiceIdGmpropertiesgmAction2$ {
  /** @deprecated use `ApiServiceIdGmpropertiesgmAction2$inboundSchema` instead. */
  export const inboundSchema = ApiServiceIdGmpropertiesgmAction2$inboundSchema;
  /** @deprecated use `ApiServiceIdGmpropertiesgmAction2$outboundSchema` instead. */
  export const outboundSchema =
    ApiServiceIdGmpropertiesgmAction2$outboundSchema;
}
