/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * An object containing api_serviceid_client_lock_flag_update_clientidenti data
 */
export type ApiServiceIdClientLockFlagUpdateClientIdenti = {
  /**
   * The flag value to be set
   *
   * @remarks
   */
  clientLocked: boolean;
};

/** @internal */
export const ApiServiceIdClientLockFlagUpdateClientIdenti$inboundSchema:
  z.ZodType<
    ApiServiceIdClientLockFlagUpdateClientIdenti,
    z.ZodTypeDef,
    unknown
  > = z.object({
    clientLocked: z.boolean(),
  });

/** @internal */
export type ApiServiceIdClientLockFlagUpdateClientIdenti$Outbound = {
  clientLocked: boolean;
};

/** @internal */
export const ApiServiceIdClientLockFlagUpdateClientIdenti$outboundSchema:
  z.ZodType<
    ApiServiceIdClientLockFlagUpdateClientIdenti$Outbound,
    z.ZodTypeDef,
    ApiServiceIdClientLockFlagUpdateClientIdenti
  > = z.object({
    clientLocked: z.boolean(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiServiceIdClientLockFlagUpdateClientIdenti$ {
  /** @deprecated use `ApiServiceIdClientLockFlagUpdateClientIdenti$inboundSchema` instead. */
  export const inboundSchema =
    ApiServiceIdClientLockFlagUpdateClientIdenti$inboundSchema;
  /** @deprecated use `ApiServiceIdClientLockFlagUpdateClientIdenti$outboundSchema` instead. */
  export const outboundSchema =
    ApiServiceIdClientLockFlagUpdateClientIdenti$outboundSchema;
  /** @deprecated use `ApiServiceIdClientLockFlagUpdateClientIdenti$Outbound` instead. */
  export type Outbound = ApiServiceIdClientLockFlagUpdateClientIdenti$Outbound;
}

export function apiServiceIdClientLockFlagUpdateClientIdentiToJSON(
  apiServiceIdClientLockFlagUpdateClientIdenti:
    ApiServiceIdClientLockFlagUpdateClientIdenti,
): string {
  return JSON.stringify(
    ApiServiceIdClientLockFlagUpdateClientIdenti$outboundSchema.parse(
      apiServiceIdClientLockFlagUpdateClientIdenti,
    ),
  );
}

export function apiServiceIdClientLockFlagUpdateClientIdentiFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiServiceIdClientLockFlagUpdateClientIdenti,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiServiceIdClientLockFlagUpdateClientIdenti$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiServiceIdClientLockFlagUpdateClientIdenti' from JSON`,
  );
}
