/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * An object containing api_serviceid_client_registration_delete data
 */
export type ApiServiceIdClientRegistrationDelete = {
  /**
   * Client ID.
   *
   * @remarks
   */
  clientId: number;
  /**
   * Client registration access token.
   *
   * @remarks
   */
  token: string;
};

/** @internal */
export const ApiServiceIdClientRegistrationDelete$inboundSchema: z.ZodType<
  ApiServiceIdClientRegistrationDelete,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientId: z.number().int(),
  token: z.string(),
});

/** @internal */
export type ApiServiceIdClientRegistrationDelete$Outbound = {
  clientId: number;
  token: string;
};

/** @internal */
export const ApiServiceIdClientRegistrationDelete$outboundSchema: z.ZodType<
  ApiServiceIdClientRegistrationDelete$Outbound,
  z.ZodTypeDef,
  ApiServiceIdClientRegistrationDelete
> = z.object({
  clientId: z.number().int(),
  token: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiServiceIdClientRegistrationDelete$ {
  /** @deprecated use `ApiServiceIdClientRegistrationDelete$inboundSchema` instead. */
  export const inboundSchema =
    ApiServiceIdClientRegistrationDelete$inboundSchema;
  /** @deprecated use `ApiServiceIdClientRegistrationDelete$outboundSchema` instead. */
  export const outboundSchema =
    ApiServiceIdClientRegistrationDelete$outboundSchema;
  /** @deprecated use `ApiServiceIdClientRegistrationDelete$Outbound` instead. */
  export type Outbound = ApiServiceIdClientRegistrationDelete$Outbound;
}

export function apiServiceIdClientRegistrationDeleteToJSON(
  apiServiceIdClientRegistrationDelete: ApiServiceIdClientRegistrationDelete,
): string {
  return JSON.stringify(
    ApiServiceIdClientRegistrationDelete$outboundSchema.parse(
      apiServiceIdClientRegistrationDelete,
    ),
  );
}

export function apiServiceIdClientRegistrationDeleteFromJSON(
  jsonString: string,
): SafeParseResult<ApiServiceIdClientRegistrationDelete, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApiServiceIdClientRegistrationDelete$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiServiceIdClientRegistrationDelete' from JSON`,
  );
}
