/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * An object containing api_serviceid_auth_revocation data
 */
export type ApiServiceIdAuthRevocation = {
  /**
   * OAuth 2.0 token revocation request parameters which are the request parameters that the OAuth 2.0 token revocation endpoint
   *
   * @remarks
   * ([RFC 7009](https://datatracker.ietf.org/doc/html/rfc7009)) of the authorization server implementation received from the
   * client application.
   *
   * The value of parameters is the entire entity body (which is formatted in `application/x-www-form-urlencoded`) of the request
   * from the client application.
   */
  parameters: string;
  /**
   * The client ID extracted from `Authorization` header of the revocation request from the client application.
   *
   * @remarks
   *
   * If the revocation endpoint of the authorization server implementation supports Basic Authentication
   * as a means of client authentication, and the request from the client application contains its client ID in
   * `Authorization` header, the value should be extracted and set to this parameter.
   */
  clientId?: number | undefined;
  /**
   * The client secret extracted from `Authorization` header of the revocation request from the client application.
   *
   * @remarks
   *
   * If the revocation endpoint of the authorization server implementation supports basic authentication as a means of
   * client authentication, and the request from the client application contained its client secret in `Authorization` header,
   * the value should be extracted and set to this parameter.
   */
  clientSecret?: string | undefined;
  /**
   * The client certificate used in the TLS connection between the client application and the revocation endpoint.
   *
   * @remarks
   */
  clientCertificate?: string | undefined;
  /**
   * The certificate path presented by the client during client authentication.
   *
   * @remarks
   */
  clientCertificatePath?: string | undefined;
};

/** @internal */
export const ApiServiceIdAuthRevocation$inboundSchema: z.ZodType<
  ApiServiceIdAuthRevocation,
  z.ZodTypeDef,
  unknown
> = z.object({
  parameters: z.string(),
  clientId: z.number().int().optional(),
  clientSecret: z.string().optional(),
  clientCertificate: z.string().optional(),
  clientCertificatePath: z.string().optional(),
});

/** @internal */
export type ApiServiceIdAuthRevocation$Outbound = {
  parameters: string;
  clientId?: number | undefined;
  clientSecret?: string | undefined;
  clientCertificate?: string | undefined;
  clientCertificatePath?: string | undefined;
};

/** @internal */
export const ApiServiceIdAuthRevocation$outboundSchema: z.ZodType<
  ApiServiceIdAuthRevocation$Outbound,
  z.ZodTypeDef,
  ApiServiceIdAuthRevocation
> = z.object({
  parameters: z.string(),
  clientId: z.number().int().optional(),
  clientSecret: z.string().optional(),
  clientCertificate: z.string().optional(),
  clientCertificatePath: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiServiceIdAuthRevocation$ {
  /** @deprecated use `ApiServiceIdAuthRevocation$inboundSchema` instead. */
  export const inboundSchema = ApiServiceIdAuthRevocation$inboundSchema;
  /** @deprecated use `ApiServiceIdAuthRevocation$outboundSchema` instead. */
  export const outboundSchema = ApiServiceIdAuthRevocation$outboundSchema;
  /** @deprecated use `ApiServiceIdAuthRevocation$Outbound` instead. */
  export type Outbound = ApiServiceIdAuthRevocation$Outbound;
}

export function apiServiceIdAuthRevocationToJSON(
  apiServiceIdAuthRevocation: ApiServiceIdAuthRevocation,
): string {
  return JSON.stringify(
    ApiServiceIdAuthRevocation$outboundSchema.parse(apiServiceIdAuthRevocation),
  );
}

export function apiServiceIdAuthRevocationFromJSON(
  jsonString: string,
): SafeParseResult<ApiServiceIdAuthRevocation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiServiceIdAuthRevocation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiServiceIdAuthRevocation' from JSON`,
  );
}
