/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The grant management action of the device authorization request.
 *
 * @remarks
 *
 * The `grant_management_action` request parameter is defined in
 * [Grant Management for OAuth 2.0](https://openid.net/specs/fapi-grant-management.html).
 */
export const ApiServiceIdGmpropertiesgmAction1 = {
  Create: "CREATE",
  Query: "QUERY",
  Replace: "REPLACE",
  Revoke: "REVOKE",
  Merge: "MERGE",
} as const;
/**
 * The grant management action of the device authorization request.
 *
 * @remarks
 *
 * The `grant_management_action` request parameter is defined in
 * [Grant Management for OAuth 2.0](https://openid.net/specs/fapi-grant-management.html).
 */
export type ApiServiceIdGmpropertiesgmAction1 = ClosedEnum<
  typeof ApiServiceIdGmpropertiesgmAction1
>;

/** @internal */
export const ApiServiceIdGmpropertiesgmAction1$inboundSchema: z.ZodNativeEnum<
  typeof ApiServiceIdGmpropertiesgmAction1
> = z.nativeEnum(ApiServiceIdGmpropertiesgmAction1);

/** @internal */
export const ApiServiceIdGmpropertiesgmAction1$outboundSchema: z.ZodNativeEnum<
  typeof ApiServiceIdGmpropertiesgmAction1
> = ApiServiceIdGmpropertiesgmAction1$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiServiceIdGmpropertiesgmAction1$ {
  /** @deprecated use `ApiServiceIdGmpropertiesgmAction1$inboundSchema` instead. */
  export const inboundSchema = ApiServiceIdGmpropertiesgmAction1$inboundSchema;
  /** @deprecated use `ApiServiceIdGmpropertiesgmAction1$outboundSchema` instead. */
  export const outboundSchema =
    ApiServiceIdGmpropertiesgmAction1$outboundSchema;
}
