/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AuthorizationIssueRequest = {};

/** @internal */
export const AuthorizationIssueRequest$inboundSchema: z.ZodType<
  AuthorizationIssueRequest,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type AuthorizationIssueRequest$Outbound = {};

/** @internal */
export const AuthorizationIssueRequest$outboundSchema: z.ZodType<
  AuthorizationIssueRequest$Outbound,
  z.ZodTypeDef,
  AuthorizationIssueRequest
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthorizationIssueRequest$ {
  /** @deprecated use `AuthorizationIssueRequest$inboundSchema` instead. */
  export const inboundSchema = AuthorizationIssueRequest$inboundSchema;
  /** @deprecated use `AuthorizationIssueRequest$outboundSchema` instead. */
  export const outboundSchema = AuthorizationIssueRequest$outboundSchema;
  /** @deprecated use `AuthorizationIssueRequest$Outbound` instead. */
  export type Outbound = AuthorizationIssueRequest$Outbound;
}

export function authorizationIssueRequestToJSON(
  authorizationIssueRequest: AuthorizationIssueRequest,
): string {
  return JSON.stringify(
    AuthorizationIssueRequest$outboundSchema.parse(authorizationIssueRequest),
  );
}

export function authorizationIssueRequestFromJSON(
  jsonString: string,
): SafeParseResult<AuthorizationIssueRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthorizationIssueRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthorizationIssueRequest' from JSON`,
  );
}
