/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type BackchannelAuthenticationRequest = {};

/** @internal */
export const BackchannelAuthenticationRequest$inboundSchema: z.ZodType<
  BackchannelAuthenticationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type BackchannelAuthenticationRequest$Outbound = {};

/** @internal */
export const BackchannelAuthenticationRequest$outboundSchema: z.ZodType<
  BackchannelAuthenticationRequest$Outbound,
  z.ZodTypeDef,
  BackchannelAuthenticationRequest
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BackchannelAuthenticationRequest$ {
  /** @deprecated use `BackchannelAuthenticationRequest$inboundSchema` instead. */
  export const inboundSchema = BackchannelAuthenticationRequest$inboundSchema;
  /** @deprecated use `BackchannelAuthenticationRequest$outboundSchema` instead. */
  export const outboundSchema = BackchannelAuthenticationRequest$outboundSchema;
  /** @deprecated use `BackchannelAuthenticationRequest$Outbound` instead. */
  export type Outbound = BackchannelAuthenticationRequest$Outbound;
}

export function backchannelAuthenticationRequestToJSON(
  backchannelAuthenticationRequest: BackchannelAuthenticationRequest,
): string {
  return JSON.stringify(
    BackchannelAuthenticationRequest$outboundSchema.parse(
      backchannelAuthenticationRequest,
    ),
  );
}

export function backchannelAuthenticationRequestFromJSON(
  jsonString: string,
): SafeParseResult<BackchannelAuthenticationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BackchannelAuthenticationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BackchannelAuthenticationRequest' from JSON`,
  );
}
