/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ClientRegistrationUpdateRequest = {};

/** @internal */
export const ClientRegistrationUpdateRequest$inboundSchema: z.ZodType<
  ClientRegistrationUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type ClientRegistrationUpdateRequest$Outbound = {};

/** @internal */
export const ClientRegistrationUpdateRequest$outboundSchema: z.ZodType<
  ClientRegistrationUpdateRequest$Outbound,
  z.ZodTypeDef,
  ClientRegistrationUpdateRequest
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ClientRegistrationUpdateRequest$ {
  /** @deprecated use `ClientRegistrationUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = ClientRegistrationUpdateRequest$inboundSchema;
  /** @deprecated use `ClientRegistrationUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = ClientRegistrationUpdateRequest$outboundSchema;
  /** @deprecated use `ClientRegistrationUpdateRequest$Outbound` instead. */
  export type Outbound = ClientRegistrationUpdateRequest$Outbound;
}

export function clientRegistrationUpdateRequestToJSON(
  clientRegistrationUpdateRequest: ClientRegistrationUpdateRequest,
): string {
  return JSON.stringify(
    ClientRegistrationUpdateRequest$outboundSchema.parse(
      clientRegistrationUpdateRequest,
    ),
  );
}

export function clientRegistrationUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<ClientRegistrationUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientRegistrationUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientRegistrationUpdateRequest' from JSON`,
  );
}
