/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type DeviceAuthorizationRequest = {};

/** @internal */
export const DeviceAuthorizationRequest$inboundSchema: z.ZodType<
  DeviceAuthorizationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type DeviceAuthorizationRequest$Outbound = {};

/** @internal */
export const DeviceAuthorizationRequest$outboundSchema: z.ZodType<
  DeviceAuthorizationRequest$Outbound,
  z.ZodTypeDef,
  DeviceAuthorizationRequest
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeviceAuthorizationRequest$ {
  /** @deprecated use `DeviceAuthorizationRequest$inboundSchema` instead. */
  export const inboundSchema = DeviceAuthorizationRequest$inboundSchema;
  /** @deprecated use `DeviceAuthorizationRequest$outboundSchema` instead. */
  export const outboundSchema = DeviceAuthorizationRequest$outboundSchema;
  /** @deprecated use `DeviceAuthorizationRequest$Outbound` instead. */
  export type Outbound = DeviceAuthorizationRequest$Outbound;
}

export function deviceAuthorizationRequestToJSON(
  deviceAuthorizationRequest: DeviceAuthorizationRequest,
): string {
  return JSON.stringify(
    DeviceAuthorizationRequest$outboundSchema.parse(deviceAuthorizationRequest),
  );
}

export function deviceAuthorizationRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeviceAuthorizationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeviceAuthorizationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeviceAuthorizationRequest' from JSON`,
  );
}
