/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type IntrospectionStandardRequest = {};

/** @internal */
export const IntrospectionStandardRequest$inboundSchema: z.ZodType<
  IntrospectionStandardRequest,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type IntrospectionStandardRequest$Outbound = {};

/** @internal */
export const IntrospectionStandardRequest$outboundSchema: z.ZodType<
  IntrospectionStandardRequest$Outbound,
  z.ZodTypeDef,
  IntrospectionStandardRequest
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IntrospectionStandardRequest$ {
  /** @deprecated use `IntrospectionStandardRequest$inboundSchema` instead. */
  export const inboundSchema = IntrospectionStandardRequest$inboundSchema;
  /** @deprecated use `IntrospectionStandardRequest$outboundSchema` instead. */
  export const outboundSchema = IntrospectionStandardRequest$outboundSchema;
  /** @deprecated use `IntrospectionStandardRequest$Outbound` instead. */
  export type Outbound = IntrospectionStandardRequest$Outbound;
}

export function introspectionStandardRequestToJSON(
  introspectionStandardRequest: IntrospectionStandardRequest,
): string {
  return JSON.stringify(
    IntrospectionStandardRequest$outboundSchema.parse(
      introspectionStandardRequest,
    ),
  );
}

export function introspectionStandardRequestFromJSON(
  jsonString: string,
): SafeParseResult<IntrospectionStandardRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IntrospectionStandardRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IntrospectionStandardRequest' from JSON`,
  );
}
