/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Values for the `client_registration_types` RP metadata and the
 *
 * @remarks
 *  `client_registration_types_supported` OP metadata that are defined in
 *  [OpenID Connect Federation 1.0](https://openid.net/specs/openid-connect-federation-1_0.html).
 */
export const ItemsClientRegistrationTypes = {
  Automatic: "AUTOMATIC",
  Explicit: "EXPLICIT",
} as const;
/**
 * Values for the `client_registration_types` RP metadata and the
 *
 * @remarks
 *  `client_registration_types_supported` OP metadata that are defined in
 *  [OpenID Connect Federation 1.0](https://openid.net/specs/openid-connect-federation-1_0.html).
 */
export type ItemsClientRegistrationTypes = ClosedEnum<
  typeof ItemsClientRegistrationTypes
>;

/** @internal */
export const ItemsClientRegistrationTypes$inboundSchema: z.ZodNativeEnum<
  typeof ItemsClientRegistrationTypes
> = z.nativeEnum(ItemsClientRegistrationTypes);

/** @internal */
export const ItemsClientRegistrationTypes$outboundSchema: z.ZodNativeEnum<
  typeof ItemsClientRegistrationTypes
> = ItemsClientRegistrationTypes$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ItemsClientRegistrationTypes$ {
  /** @deprecated use `ItemsClientRegistrationTypes$inboundSchema` instead. */
  export const inboundSchema = ItemsClientRegistrationTypes$inboundSchema;
  /** @deprecated use `ItemsClientRegistrationTypes$outboundSchema` instead. */
  export const outboundSchema = ItemsClientRegistrationTypes$outboundSchema;
}
